### PR TITLE
Development

### PR DESCRIPTION
**Pull request by cristian-ungureanu**

### CODE REVIEW

**Comment by rodica-andronache** [comment]
@cristian-ungureanu here, if the stuff with tgmp can't be merged yet ( I think you mentioned that ) can you please remove it, so I can merge the other stuff in the commit?

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , done

**Comment by rodica-andronache** [comment]
@cristian-ungureanu thanks. Travis is still failing. Have a look at that too

**Comment by cristian-ungureanu** [comment]
It's passing now. :)

**Pull request merged**
